--- #YAML:1.0
name:                Memoize-Memcached
version:             0.02
abstract:            use a memcached cache to memoize functions
license:             ~
author:              
    - David Trischuk <trischuk@gmail.com>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Cache::Memcached:              0
    Carp:                          0
    Memoize:                       0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
